#!/usr/bin/env python3
"""
UPMurphi Plan Parser

Parses PDDL+ plan files generated by UPMurphi and converts them into
structured action sequences suitable for ROSPlan dispatch or standalone
simulation.

UPMurphi output format:
    ; --Plan #00001--------------------------
    ; -- Discretisation: 1.000----------------
    ; ---------------------------------------
    0.000: ( action_name param1 param2) [duration]
    0.001: ( another_action p1) [duration]
    ; ---------------------------------------
    ; --Plan duration: X.XXX, weight: NNNN----
    ; ---------------------------------------
"""

import re
import json
import sys
from dataclasses import dataclass, field, asdict
from typing import List, Optional


@dataclass
class PlanAction:
    """A single action in a UPMurphi plan."""
    timestamp: float
    action_name: str
    parameters: List[str]
    duration: float
    weight: Optional[int] = None

    @property
    def end_time(self) -> float:
        return self.timestamp + self.duration

    def to_rosplan_format(self) -> str:
        params_str = " ".join(self.parameters)
        return f"{self.timestamp:.6f}: ({self.action_name} {params_str}) [{self.duration:.6f}]"

    def to_upmurphi_format(self) -> str:
        params_str = " ".join(self.parameters)
        return f"{self.timestamp:.3f}: ( {self.action_name} {params_str}) [{self.duration:.3f}]"

    def __str__(self) -> str:
        params_str = " ".join(self.parameters)
        return (f"[t={self.timestamp:.3f}] ({self.action_name} {params_str}) "
                f"[dur={self.duration:.3f}]")


@dataclass
class Plan:
    """A complete plan parsed from UPMurphi output."""
    plan_number: int = 0
    discretisation: float = 0.0
    actions: List[PlanAction] = field(default_factory=list)
    total_duration: float = 0.0
    total_weight: int = 0

    @property
    def num_actions(self) -> int:
        return len(self.actions)

    def to_rosplan_file(self) -> str:
        lines = []
        for a in self.actions:
            lines.append(a.to_rosplan_format())
        return "\n".join(lines) + "\n"

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, ensure_ascii=False)


# Regex patterns for UPMurphi plan output
_RE_PLAN_HEADER = re.compile(r'^;\s*--Plan\s+#(\d+)')
_RE_DISCRETISATION = re.compile(r'^;\s*--\s*Discretisation:\s*([\d.]+)')
_RE_ACTION = re.compile(
    r'^([\d.]+):\s+\(\s*(.+?)\s*\)\s+\[([\d.]+)\](?:\s*;\s*weight\s*=\s*(\d+))?'
)
_RE_PLAN_DURATION = re.compile(
    r'^;\s*--Plan duration:\s*([\d.]+),\s*weight:\s*(\d+)'
)
_RE_COMMENT = re.compile(r'^\s*;')
_RE_BLANK = re.compile(r'^\s*$')


def parse_plan_file(filepath: str) -> List[Plan]:
    """Parse a UPMurphi plan output file. Returns a list of Plan objects."""
    with open(filepath, 'r', encoding='utf-8') as f:
        return parse_plan_text(f.read())


def parse_plan_text(text: str) -> List[Plan]:
    """Parse UPMurphi plan output text. Returns a list of Plan objects."""
    plans: List[Plan] = []
    current_plan: Optional[Plan] = None

    for line in text.splitlines():
        line = line.rstrip()

        m = _RE_PLAN_HEADER.match(line)
        if m:
            current_plan = Plan(plan_number=int(m.group(1)))
            plans.append(current_plan)
            continue

        if current_plan is None:
            continue

        m = _RE_DISCRETISATION.match(line)
        if m:
            current_plan.discretisation = float(m.group(1))
            continue

        m = _RE_ACTION.match(line)
        if m:
            timestamp = float(m.group(1))
            action_parts = m.group(2).strip().split()
            action_name = action_parts[0]
            parameters = action_parts[1:] if len(action_parts) > 1 else []
            duration = float(m.group(3))
            weight = int(m.group(4)) if m.group(4) else None
            current_plan.actions.append(PlanAction(
                timestamp=timestamp,
                action_name=action_name,
                parameters=parameters,
                duration=duration,
                weight=weight,
            ))
            continue

        m = _RE_PLAN_DURATION.match(line)
        if m:
            current_plan.total_duration = float(m.group(1))
            current_plan.total_weight = int(m.group(2))
            continue

    return plans


def main():
    """CLI entry point: parse a plan file and print results."""
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <plan_file> [--json|--rosplan|--summary]")
        sys.exit(1)

    filepath = sys.argv[1]
    fmt = sys.argv[2] if len(sys.argv) > 2 else "--summary"

    plans = parse_plan_file(filepath)

    if not plans:
        print("No plans found in file.")
        sys.exit(1)

    for plan in plans:
        if fmt == "--json":
            print(plan.to_json())
        elif fmt == "--rosplan":
            print(plan.to_rosplan_file())
        else:
            print(f"=== Plan #{plan.plan_number:05d} ===")
            print(f"  Discretisation: {plan.discretisation}")
            print(f"  Actions: {plan.num_actions}")
            print(f"  Duration: {plan.total_duration}")
            print(f"  Weight: {plan.total_weight}")
            for a in plan.actions:
                print(f"  {a}")


if __name__ == "__main__":
    main()
